apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: task-pv-volume
  namespace: test 
  labels:
    type: local
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce 
  capacity:
    storage: 10Gi
  #persistentVolumeReclaimPolicy: Recycle 
  hostPath:
    path: "/mnt/data" 
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: task-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: task-pv-claim 
  namespace: test
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      type: local
