# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: task-pv-storage
#   namespace: test
# spec:
#   storageClassName: slow
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce 
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Recycle
#   mountOptions:
#     - hard 
#     - nfsvers=4.1
#   nfs:
#     path: /tmp
#     server: 10.106.138.218

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 10.106.138.218


