apiVersion: v1 
kind: Pod
metadata:
  name: volume-test
  namespace: test

spec:
  containers:
    - name: container-test 
      image: busybox:1.28 
      volumeMounts:
        - name: all-in-one 
          mountPath: "/projectvolume"
          readOnly: true
  volumes:
    - name: all-in-one
      projected:
        sources:
          - secret:              
              name: mysecret
              items:
                - key: username
                  path: mygroup/myusername
          - downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
                - path: "cpu_limit"
                  resourceFieldRef:
                    containerName: container-test
                    resource: limits.cpu
          - configMap:
              name: myconfigmap
              items:
                - key: config
                  path: my-group/my-config
          