apiVersion: v1
kind: Pod 
metadata:
  name: pod1
  namespace: test1
  labels:
    name: pod1
spec:
  containers:
    - name: ubuntu-pod
      image: ubuntu
      command:
        - "sleep"
        - "604800"
      ports:
        - containerPort: 8001

