apiVersion: v1
kind: Pod 
metadata:
  name: pod2
  namespace: test2
  labels:
    name: pod2
spec:
  containers:
    - name: ubuntu-pod
      image: ubuntu
      command:
        - "sleep"
        - "604800"
      ports:
        - containerPort: 8002

