apiVersion: v1
kind: Pod 
metadata:
  name: configmap-example-pod
spec:
  nodeSelector:
    type: node1
  containers:
    - name: configmap-example-busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
        - configMapRef:
            name: game-config-example
  restartPolicy: Never

