apiVersion: v1
kind: Pod 
metadata:
  name: configmap-volume-pod
spec:
  # nodeSelector:
  #   type: node1
  containers:
    - name: configmap-volume-example-busybox
      image: k8s.gcr.io/busybox
      resources:
        requests:
          cpu: "0.6"
          memory: "100Mi"
        limits:
          cpu: "0.6"
          memory: "100Mi"
      command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
          name: game-configmap-example
  restartPolicy: Never