apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: php-apache
spec:
   replicas: 5
   strategy:
     type: Recreate
   selector:
     matchLabels:
       app: php-apache
   template:
     metadata:
       labels:
         app: php-apache
     spec:
       containers:
         - name: php-apache
           image: registry.k8s.io/hpa-example
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 80
           resources:
             requests:
               cpu: 100m
               memory: 200Mi
             limits:
               cpu: 100m 
               memory: 200Mi 
--- 
apiVersion: v1 
kind: Service
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  ports: 
    - port: 80
      targetPort: 9000
  selector:
    app: php-apache



        