apiVersion: v1 
kind: Pod 
metadata:
  name: pod4
  namespace: test
  labels:
    app: web
spec:
  containers:
    - name: mem-demo-ctr
      image: polinux/stress
      resources:
        requests:
          memory: "128Mi"
        limits:
          memory: "200Mi"
      command: ["stress"]
      args: ["--vm","1","--vm-bytes","150m","--vm-hang","1"]
     