apiVersion: v1
kind: Pod 
metadata:
  name: cpu-memo
  namespace: test
  labels:
    app: web
spec:
  containers:
    - name: cpu-memo-str
      image: nginx
      resources:
        requests:
          example.com/dongle: 3
        limits:
          example.com/dongle: 3
          
    