apiVersion: v1
kind: Pod 
metadata:
  name: pod1
  labels:
    app: web
spec:
  containers:
    - name: redis-db 
      image: redis 
      volumeMounts:
        - name: storage
          mountPath: /data/redis 
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.6"
        limits:
          memory: "200Mi"
          cpu: "0.6"
  volumes:
    - name: storage
      emptyDir: {}
