apiVersion: v1
kind: Pod 
metadata:
  name: redis-and-nginx
  namespace: test
  labels:
    app: db
spec:
  containers:
    - name: redis-db
      image: redis
      volumeMounts:
        - name: storage
          mountPath: /data/redis
    - name: nginx-db
      image: nginx
      volumeMounts:
        - name: storage
          mountPath: /data1/nginx
  volumes:
    - name: storage
      emptyDir: {}